image:
  repository: ${CI_REGISTRY_IMAGE}/frontend
  tag: ${IMAGE_TAG}

deployment:

  port: ${PORT}

  resources:
    limits:
      cpu: ${APP_RESOURCE_CPU_LIMIT}
      memory: ${APP_RESOURCE_MEMORY_LIMIT}
    requests:
      cpu: ${APP_RESOURCE_CPU_REQUEST}
      memory: ${APP_RESOURCE_MEMORY_REQUEST}

  livenessProbe:
    path: /
    periodSeconds: 5
    port: ${PORT}
  readinessProbe:
    path: /
    periodSeconds: 5
    port: ${PORT}

service:
  port: ${PORT}
  targetPort: ${PORT}

ingress:
  enabled: true
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "azure/application-gateway"
  hosts:
    - host: ${FRONTEND_HOST}
      paths:
        - path: /
          servicePort: ${PORT}
  tls:
    - hosts:
        - ${APP_URL}
      secretName: work-in-france-crt

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
