# See https://github.com/SocialGouv/helm-charts/tree/master/charts/app

image:
  repository: ${CI_REGISTRY_IMAGE}
  tag: ${IMAGE_TAG}

fullnameOverride: wif

deployment:

  livenessProbe:
    initialDelaySeconds: 30

  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 64Mi

  env:
    - name: DS_AGGREGATOR_API_URL
      value: "https://ds-aggregator-api.incubateur.social.gouv.fr"
    - name: PORT
      value: "${PORT}"
    - name: NODE_ENV
      value: production

ingress:
  enabled: true
